/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eglise;
import com.eglise.UI.*;
import java.awt.BorderLayout;

/**
 *
 * @author christalin
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.routerPanel.setLayout(new BorderLayout());
        this.routerPanel.removeAll();
        this.routerPanel.add(new HomePanel(), BorderLayout.CENTER);
        this.routerPanel.revalidate();
        this.routerPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        routerPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        egliseBtn1 = new javax.swing.JMenu();
        egliseBtn = new javax.swing.JMenu();
        entreeBtn = new javax.swing.JMenu();
        sortieBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        routerPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout routerPanelLayout = new javax.swing.GroupLayout(routerPanel);
        routerPanel.setLayout(routerPanelLayout);
        routerPanelLayout.setHorizontalGroup(
            routerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        routerPanelLayout.setVerticalGroup(
            routerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(250, 32768));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(100, 50));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(100, 50));

        egliseBtn1.setText("Acceuil");
        egliseBtn1.setPreferredSize(new java.awt.Dimension(100, 30));
        egliseBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePage(evt);
            }
        });
        jMenuBar1.add(egliseBtn1);

        egliseBtn.setText("Eglise");
        egliseBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        egliseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                egliseMenu(evt);
            }
        });
        jMenuBar1.add(egliseBtn);

        entreeBtn.setText("Entree");
        entreeBtn.setMinimumSize(new java.awt.Dimension(100, 50));
        entreeBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        entreeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entreeMenu(evt);
            }
        });
        jMenuBar1.add(entreeBtn);

        sortieBtn.setText("Sortie");
        sortieBtn.setMinimumSize(new java.awt.Dimension(100, 50));
        sortieBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        sortieBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortieMenu(evt);
            }
        });
        jMenuBar1.add(sortieBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(routerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(routerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePage
        // TODO add your handling code here:
        this.routerPanel.setLayout(new BorderLayout());
        this.routerPanel.removeAll();
        this.routerPanel.add(new HomePanel(), BorderLayout.CENTER);
        this.routerPanel.revalidate();
        this.routerPanel.repaint();
    }//GEN-LAST:event_homePage

    private void egliseMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_egliseMenu
        // TODO add your handling code here:
        this.routerPanel.setLayout(new BorderLayout());
        this.routerPanel.removeAll();
        this.routerPanel.add(new EglisePanel(), BorderLayout.CENTER);
        this.routerPanel.revalidate();
        this.routerPanel.repaint();
    }//GEN-LAST:event_egliseMenu

    private void entreeMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entreeMenu
        // TODO add your handling code here:
        this.routerPanel.setLayout(new BorderLayout());
        this.routerPanel.removeAll();
        this.routerPanel.add(new EntreePanel(), BorderLayout.CENTER);
        this.routerPanel.revalidate();
        this.routerPanel.repaint();
    }//GEN-LAST:event_entreeMenu

    private void sortieMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortieMenu
        // TODO add your handling code here:
        this.routerPanel.setLayout(new BorderLayout());
        this.routerPanel.removeAll();
        this.routerPanel.add(new SortiePanel(), BorderLayout.CENTER);
        this.routerPanel.revalidate();
        this.routerPanel.repaint();
    }//GEN-LAST:event_sortieMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu egliseBtn;
    private javax.swing.JMenu egliseBtn1;
    private javax.swing.JMenu entreeBtn;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel routerPanel;
    private javax.swing.JMenu sortieBtn;
    // End of variables declaration//GEN-END:variables
}
