/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.eglise.UI;
import com.eglise.Model.EgliseModel;

/**
 *
 * @author christalin
 */
public class EglisePanel extends javax.swing.JPanel {

    /**
     * Creates new form EglisePanel
     */
    public EglisePanel() {
        initComponents();
        showPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasEglise = new javax.swing.JPanel();
        egliseName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        soldeValue = new javax.swing.JLabel();
        notHasEglise = new javax.swing.JPanel();
        information = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createEgliseBtn = new javax.swing.JButton();
        egliseNameField = new javax.swing.JTextField();

        egliseName.setFont(new java.awt.Font("Quicksand Light", 3, 24)); // NOI18N
        egliseName.setForeground(new java.awt.Color(0, 0, 102));
        egliseName.setText("Nom de l'Eglise");

        jLabel1.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jLabel1.setText("Solde :");

        soldeValue.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        soldeValue.setText("0 Ar");

        javax.swing.GroupLayout hasEgliseLayout = new javax.swing.GroupLayout(hasEglise);
        hasEglise.setLayout(hasEgliseLayout);
        hasEgliseLayout.setHorizontalGroup(
            hasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasEgliseLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(hasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egliseName, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hasEgliseLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(soldeValue)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        hasEgliseLayout.setVerticalGroup(
            hasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasEgliseLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(egliseName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(soldeValue))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        information.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        information.setText("Aucune Eglise n'est enregistré");

        jLabel3.setText("Nom de l' Eglise");

        createEgliseBtn.setText("Créer l' Eglise");
        createEgliseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEglise(evt);
            }
        });

        egliseNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egliseNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notHasEgliseLayout = new javax.swing.GroupLayout(notHasEglise);
        notHasEglise.setLayout(notHasEgliseLayout);
        notHasEgliseLayout.setHorizontalGroup(
            notHasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notHasEgliseLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(notHasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notHasEgliseLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(egliseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(information)
                    .addComponent(createEgliseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        notHasEgliseLayout.setVerticalGroup(
            notHasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notHasEgliseLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(information)
                .addGap(27, 27, 27)
                .addGroup(notHasEgliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(egliseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(createEgliseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasEglise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(notHasEglise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(hasEglise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(notHasEglise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void egliseNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egliseNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egliseNameFieldActionPerformed

    private void addEglise(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEglise
        // TODO add your handling code here:
        String eglise_name = this.egliseNameField.getText();
        EgliseModel eglise = new EgliseModel(eglise_name);
        
        if(eglise.createEglise()==1){
            this.showPanel();
                    
        }
    }//GEN-LAST:event_addEglise
    
    private void showPanel(){
        boolean exist = EgliseModel.hasEglise();
        System.out.println(exist);
        if(exist){
            this.notHasEglise.setVisible(false);
            this.hasEglise.setVisible(true);
            EgliseModel eglise = EgliseModel.getEglise();
            this.egliseName.setText(eglise.design);
            this.soldeValue.setText(String.valueOf(eglise.solde)+" Ar");
        }
        else{
            this.hasEglise.setVisible(false);
            this.notHasEglise.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEgliseBtn;
    public javax.swing.JLabel egliseName;
    public javax.swing.JTextField egliseNameField;
    public javax.swing.JPanel hasEglise;
    private javax.swing.JLabel information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel notHasEglise;
    public javax.swing.JLabel soldeValue;
    // End of variables declaration//GEN-END:variables
}
