/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.eglise.UI;
import com.eglise.Model.Entree;

/**
 *
 * @author christalin
 */
public class EntreePanel extends javax.swing.JPanel {

    /**
     * Creates new form EntreePanel
     */
    public EntreePanel() {
        initComponents();
        try{
            fetchList();
        }
        catch(Exception E){
            this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(new String[][] {{"Aucun","données","disponible"}},new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE"})) ;
            System.out.println(E);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entreeTable = new javax.swing.JTable();

        entreeTable.setBackground(new java.awt.Color(204, 255, 255));
        entreeTable.setFont(new java.awt.Font("Quicksand Light", 3, 18)); // NOI18N
        entreeTable.setForeground(new java.awt.Color(51, 51, 51));
        entreeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_ENTREE", "MOTIF", "MONTANT", "DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(entreeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fetchList(){
        Entree[] entrees = Entree.listEntree();
        String[][] data = new String[entrees.length][4];
        for (int i = 0; i < entrees.length; i++){
            data[i][0] = String.valueOf(entrees[i].idEntree);
            data[i][1] = entrees[i].motif;
            data[i][2] = String.valueOf(entrees[i].montantEntree);
            data[i][3] = entrees[i].dateEntree.toString();
        }
        if(entrees.length == 0){
            this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(new String[][] {},new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE"})) ;
        }else{
            this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(data,new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE"})) ;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable entreeTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
