/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.eglise.UI;
import com.eglise.Model.Entree;
import com.eglise.Model.EgliseModel;
import com.eglise.Model.Sortie;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author christalin
 */
public class EntreePanel extends javax.swing.JPanel {

    /**
     * Creates new form EntreePanel
     */
    public EntreePanel() {
        initComponents();
        try{
            fetchList();
        }
        catch(Exception E){
            this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(new String[][] {{"Aucun","données","disponible"}},new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE", "ACTION"})) ;
            System.out.println(E);
        }
        this.entreeTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        this.entreeTable.getColumnModel().getColumn(1).setPreferredWidth(300);
        this.entreeTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        this.entreeTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        this.entreeTable.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entreeTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        motifField = new javax.swing.JTextField();
        montantField = new javax.swing.JTextField();
        ajoutBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        rechercheField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        entreeTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        entreeTable.setForeground(new java.awt.Color(51, 51, 51));
        entreeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_ENTREE", "MOTIF", "MONTANT", "DATE", "SUPPRIMER", "MODIFIER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        entreeTable.setRowHeight(40);
        entreeTable.setRowMargin(5);
        entreeTable.setRowSelectionAllowed(false);
        entreeTable.setShowGrid(true);
        entreeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(entreeTable);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Quicksand Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Ajout d'une Entrée en Caisse");

        jLabel2.setText("Motif :");

        jLabel3.setText("Montant entrée :");

        motifField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifFieldActionPerformed(evt);
            }
        });

        montantField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantFieldActionPerformed(evt);
            }
        });

        ajoutBtn.setText("Ajouter");
        ajoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutEntree(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ajoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(montantField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(motifField))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(motifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(montantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(ajoutBtn)
                .addGap(28, 28, 28)
                .addComponent(infoLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jButton1.setText("Rechercher");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetchList(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rechercheField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rechercheField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void motifFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motifFieldActionPerformed

    private void montantFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantFieldActionPerformed

    private void ajoutEntree(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutEntree
        // TODO add your handling code here:
        try{
            Entree entree = new Entree(this.motifField.getText(),Integer.parseInt(this.montantField.getText()));
            if (EgliseModel.hasEglise()){
                EgliseModel eglise = EgliseModel.getEglise();
                eglise.addSolde(Integer.parseInt(this.montantField.getText()));
                int id = entree.create();
                if (id != 0) entree.idEntree = id;
                this.removeAll();
                initComponents();
                this.infoLabel.setText("Ajout Effectué avec succès");
                this.infoLabel.setForeground(Color.darkGray);
            }
            else{
                this.infoLabel.setText("Veillez d'abord créer une Eglise pour effectuer une entrée en caisse");
                this.infoLabel.setForeground(Color.red);
            }
            try{
                fetchList();
            }
            catch(Exception E){
                this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(new String[][] {{"Aucun","données","disponible"}},new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE"})) ;
                System.out.println(E);
            }
        }
        catch(NumberFormatException E){
            this.infoLabel.setText("Veillez Entrer un montant valide.");
            this.infoLabel.setForeground(Color.red);
            System.out.println(E);
        }
    }//GEN-LAST:event_ajoutEntree

    private void fetchList(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetchList
        // TODO add your handling code here:
        fetchList();
    }//GEN-LAST:event_fetchList

    private void fetchList(){
        String motif_like = this.rechercheField.getText();
        System.out.println(motif_like.isEmpty());
        Entree[] entrees;
        if(motif_like.isEmpty()){
            entrees = Entree.listEntree();
        }
        else
            entrees = Entree.listEntree(motif_like);
        String[][] data = new String[entrees.length][5];
        for (int i = 0; i < entrees.length; i++){
            data[i][0] = String.valueOf(entrees[i].idEntree);
            data[i][1] = entrees[i].motif;
            data[i][2] = String.valueOf(entrees[i].montantEntree);
            data[i][3] = entrees[i].dateEntree.toString();
            data[i][4] = "Supprimer";
        }
        if(entrees.length == 0){
                this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(new String[][] {},new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE","SUPPRIMER","MODIFIER"})) ;
        }else{
            this.entreeTable.setModel(new javax.swing.table.DefaultTableModel(data,new String [] {"ID_ENTREE", "MOTIF", "MONTANT", "DATE","SUPPRIMER","MODIFIER"})) ;
            this.entreeTable.getColumn("SUPPRIMER").setCellRenderer(new ButtonRenderer());
            this.entreeTable.getColumn("SUPPRIMER").setCellEditor(new ButtonEditor(new JCheckBox()));
            this.entreeTable.getColumn("MODIFIER").setCellRenderer(new ButtonModifyRenderer());
            this.entreeTable.getColumn("MODIFIER").setCellEditor(new ButtonModifyEditor(new JCheckBox()));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutBtn;
    public javax.swing.JTable entreeTable;
    public javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField montantField;
    public javax.swing.JTextField motifField;
    private javax.swing.JTextField rechercheField;
    // End of variables declaration//GEN-END:variables
}


class ButtonRenderer extends JButton implements TableCellRenderer{
    public ButtonRenderer(){
        this.setOpaque(true);
    }
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
        this.setText((value==null)?"Action":value.toString());
        return this;
    }
}

class ButtonEditor extends DefaultCellEditor{
    private JButton button;
    private String label;
    private boolean clicked;
    private JTable table;
    private int row;
    
    public ButtonEditor(JCheckBox checkBox){
        super(checkBox);
        button = new JButton();
        button.setOpaque(true);
        
        button.addActionListener(e -> fireEditingStopped());
    }
    
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column){
        this.table = table;
        this.row = row;
        label = (value==null)?"Action" : value.toString();
        button.setText(label);
        clicked = true;
        return button;
    }
    public Object getCellEditorValue(){
        if(clicked){
            String id = table.getValueAt(row, 0).toString();
            int choix = JOptionPane.showConfirmDialog(button, "Supprimer "+id+" ?","Spprimer",JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(choix == JOptionPane.YES_OPTION){
                Entree entree = new Entree(Integer.parseInt(id));
                int is_deleted = entree.delete();
                if(is_deleted == 1)
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                else
                    JOptionPane.showMessageDialog(button, "Suppression echouée, solde inssuffisant");
            }
        }
        clicked = false;
        return label;
    }
    public boolean stopCellEditing(){
        clicked = false;
        return super.stopCellEditing();
    }
}

class ButtonModifyRenderer extends JButton implements TableCellRenderer{
    public ButtonModifyRenderer(){
        this.setOpaque(true);
    }
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
        this.setText((value==null)?"Modifier":value.toString());
        return this;
    }
}
class ButtonModifyEditor extends DefaultCellEditor{
    private JButton button;
    private String label;
    private boolean clicked;
    private JTable table;
    private int row;
    
    public ButtonModifyEditor(JCheckBox checkBox){
        super(checkBox);
        button = new JButton();
        button.setOpaque(true);
        
        button.addActionListener(e -> fireEditingStopped());
    }
    
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column){
        this.table = table;
        this.row = row;
        label = (value==null)?"Modifier" : value.toString();
        button.setText(label);
        clicked = true;
        return button;
    }
    public Object getCellEditorValue(){
        if(clicked){
            String id = table.getValueAt(row, 0).toString();
            String mot = table.getValueAt(row, 1).toString();
            int montant = Integer.parseInt(table.getValueAt(row, 2).toString());
            Date date = Date.valueOf(table.getValueAt(row, 3).toString());
            Entree entree = new Entree(Integer.parseInt(id));
            EgliseModel e = EgliseModel.getEglise();
            int m = entree.montantEntree-montant;
            if(e.solde-m < 10000){
                JOptionPane.showMessageDialog(table, "Erreur lors de la modification, Montant inssufisant");
                table.setValueAt(entree.idEntree, row, 0);
                table.setValueAt(entree.motif, row, 1);
                table.setValueAt(entree.montantEntree, row, 2);
                table.setValueAt(entree.dateEntree, row, 3);
            }
            else{
                e.addSolde(-m);
                if(entree.update(mot, date, montant)==1)
                    JOptionPane.showMessageDialog(table, "Modification effectué avec, succèss");
                else 
                    JOptionPane.showMessageDialog(table, "Erreur lors de la modification");
            }
        }
        clicked = false;
        return label;
    }
    public boolean stopCellEditing(){
        clicked = false;
        return super.stopCellEditing();
    }
}